assetsapp/urls.py
from django.urls import path
from . import views
from .views import Add_assets, AssetListView

urlpatterns = [
    path('', views.index, name='assets'),
    path('add-assets/', Add_assets.as_view(), name='add_assets'),
    path('list/<str:category>/', AssetListView.as_view(), name='asset_list'),

]

mgmtsystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('assets/', include('assetsapp.urls')),
    path('auth/', include('authentication.urls')),
]

assetsapp/models.py
from django.db import models
from authentication.models import CustomUser

STATUS = (
    ('USE','use'),
    ('DISUSE','disuse'),
    ('IDLE', 'idle'),
    )

class AssetCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Asset(models.Model):
    asset_number = models.CharField(primary_key=True, max_length=9, unique=True)
    asset_category = models.ForeignKey('AssetCategory', on_delete=models.PROTECT)
    description = models.CharField(max_length=255, blank=True)
    serial_number = models.CharField(max_length=100, unique=True)
    location = models.CharField(max_length=50)
    status = models.CharField(max_length=9, choices = STATUS, default="USE")
    purchase_date = models.DateField()
    warranty_expiry_date = models.DateField()

    def __str__(self):
        return f"{self.asset_category.name} - {self.asset_number}"

class Drive(models.Model):
    serialnumber = models.CharField(primary_key=True, max_length=255, unique=True)
    capacity = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

class Computer(models.Model):
    computer_id = models.CharField(primary_key=True, max_length=15, unique=True)
    asset = models.OneToOneField('Asset', on_delete=models.CASCADE)
    drive_serialnumber = models.ForeignKey(Drive, on_delete=models.CASCADE, null=True, blank=True)    

    def __str__(self):
        return f"Computer ID: {self.computer_id} - Asset: {self.asset}"

class Assignment(models.Model):
    asset = models.ForeignKey(Asset, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    assigned_date = models.DateField()

    def __str__(self):
        return f"{self.asset} assigned to {self.assigned_to}"

assetsapp/forms.py
from django import forms
from .models import Asset


class AssetCreationForm(forms.ModelForm):
    class Meta:
        model = Asset
        fields = ['asset_number', 'asset_category', 'description', 'serial_number', 'location', 'status', 'purchase_date', 'warranty_expiry_date']

assetsapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.views import View
from django.views.generic import ListView
from django.views.decorators.csrf import csrf_exempt
from .forms import AssetCreationForm
from .models import Asset, Computer, Assignment, AssetCategory
import csv

@login_required(login_url='/auth/login')
def index(request):
    return render(request, 'assetsapp/index.html')


class Add_assets(View):
    @csrf_exempt
    def get(self, request):
        form = AssetCreationForm(initial={'asset_number': '', 'description': '', 'serial_number': '', 'location': '', 'purchase_date': '', 'warranty_expiry_date': ''})
        return render(request, 'assetsapp/add_asset.html', {'form': form})
    
    @csrf_exempt
    def post(self, request):
        form = AssetCreationForm(request.POST)
        if form.is_valid():
            asset_id = form.cleaned_data['asset_number']
            category = form.cleaned_data['asset_category']
            serial_number = form.cleaned_data['serial_number']
            
            if Asset.objects.filter(asset_number = asset_id).exists():
                messages.error(request, 'Asset ID is already registered')
                return render(request, 'assetsapp/add_asset.html', {'form': form})
    
            if Asset.objects.filter(serial_number=serial_number).exists():
                messages.error(request, 'Serial Number is already registered')
                return render(request, 'assetsapp/add_asset.html', {'form': form})
            
            computer_id = "Z20012" + str(asset_id)
            
            asset = form.save(commit=False)
            asset.save()
            # Optionally create a Computer object
            if category.name == 'Computer':
                computer = Computer(computer_id = computer_id, asset=asset)
                computer.save()
                asset.computer = computer  # Associate the Computer object with the Asset

            # Redirect to the asset_detail view
            return redirect('asset_list')
            # return redirect('asset_detail', asset_number=asset.asset_number)

        # If the form is invalid, render the form page with errors
        return render(request, 'assetsapp/add_asset.html', {'form': form})

class AssetListView(ListView):
    model = Asset
    template_name = 'assetsapp/dashboard.html'
    context_object_name = 'assets'
    
    def get_queryset(self):
        # Retrieve the category parameter from the URL
        category_name = self.kwargs.get('category', None)
        
        if category_name:
            if category_name == 'All':
                return Asset.objects.all()
            else:
                category = get_object_or_404(AssetCategory, name=category_name)
                return Asset.objects.filter(asset_category=category)
        
        return Asset.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['asset_categories'] = AssetCategory.objects.all()
        
        return context

templates/assetsapp/add_asset.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'add_assets' %}">Add Asset</a>
                <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'asset_list' category='All' %}">View Assets</a>
            </div>
        </div>
    </div>
    <div class="col-md-7 col-lg-8">
    <h4 class="mb-3">Add Asset</h4>
    <form class="needs-validation" method="post" action="{% url 'add_assets' %}">
        {% csrf_token %}
        <div class="row g-3">
            <div class="row g-3">
                <div class="col-sm-6">
                    <label for="floatingInput" class="form-label">Asset ID</label>
                    <input type="text" class="form-control" id="assetNumber" name="asset_number" placeholder="" value="{{ form.asset_number.value }}" required>
                    <div class="invalid-feedback">
                        {{ form.errors.asset_number }}
                    </div>
                </div>
        
                <div class="col-md-6">
                    <label for="country" class="form-label">Category</label>
                    <select class="form-select" id="id_asset_category" name="asset_category" required>
                        {% for category in form.asset_category.field.choices %}
                            <option value="{{ category.0 }}">{{ category.1 }}</option>
                        {% endfor %}
                        
                    </select>
                    <div class="invalid-feedback">
                        {{ form.errors.asset_category }}
                    </div>
                </div>
            </div>

        <div class="col-12">
            <label for="Description" class="form-label">Description</label>
            <div class="input-group has-validation">
            <input type="text" class="form-control" id="assetDescription" placeholder="LENOVO ThinkCentre M60e" value="{{ form.description.value }}" required>
            <div class="invalid-feedback">
                {{ form.errors.description }}
            </div>
            </div>
        </div>

        <div class="col-12">
            <label for="cc-name" class="form-label">Serial Number</label>
            <input type="text" class="form-control" id="cc-name" name="serial_number" value="{{ form.serial_number.value }}" placeholder="ACE4_2E00_254B_7840_2EE4_ZAC00_0000_0001" required>
            <div class="invalid-feedback">
                {{ form.errors.serial_number }}
            </div>
        </div>

        <div class="col-md-6">
            <label for="cc-name" class="form-label">Location</label>
            <input type="text" class="form-control" id="cc-name" name="location" value="{{ form.location.value }}" placeholder="" required>
        </div>

        <div class="col-md-6">
            <label for="country" class="form-label">Status</label>
            <select class="form-select" id="country" name="status" required>
                {% for status_choice in form.status.field.choices %}
                    <option value="{{ status_choice.0 }}">{{ status_choice.1 }}</option>
                {% endfor %}
            </select>
            <div class="invalid-feedback">
                {{ form.errors.status }}
            </div>
        </div>

        <div class="col-md-6">
            <label for="cc-name" class="form-label">Purchase date</label>
            <input type="text" class="form-control" id="cc-name" name="purchase_date" placeholder="" value="{{ form.purchase_date.value }}" required>
            <div class="invalid-feedback">
                {{ form.errors.purchase_date }}
            </div>
        </div>

        <div class="col-md-6">
            <label for="cc-number" class="form-label">Warranty expiration date</label>
            <input type="text" class="form-control" id="cc-number" name="warranty_expiry_date" value="{{ form.warranty_expiry_date.value }}" placeholder="" required>
            <div class="invalid-feedback">
                {{ form.errors.warranty_expiry_date }}
            </div>
        </div>

        <hr class="my-4">

        <button class="w-100 btn btn-success btn-lg" type="submit">Add Asset</button>
    </form>
    {% if form.errors %}
        <div class="alert alert-danger mt-3">
            <strong>Error!</strong> Please correct the form errors below.
        </div>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/assetsapp/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Dashboard</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'add_assets' %}">Add Asset</a>
        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'asset_list' category='All' %}">View Assets</a>
      </div>
      <div class="btn-group">
          <select class="form-select" id="id_asset_category" name="asset_category" required>
            <option value="">All Categories</option>
            {% for category in asset_categories %}
                  <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
          </select>
      </div>
  </div>
</div>


  <h2>Asset List</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Category</th>
          <th scope="col">Description</th>
          <th scope="col">Serial Number</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
        {% for asset in assets|slice:":20" %}
          <tr>
            <td>{{ asset.asset_number }}</td>
            <td>{{ asset.asset_category.name }}</td>
            <td>{{ asset.description }}</td>
            <td>{{ asset.serial_number }}</td>
            <td>{{ asset.status }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/assetsapp/index.html
{% extends "base.html" %}

{% block content %}

<div class= "container mt-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'add_assets' %}">Add Asset</a>
                <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'asset_list' category='All' %}">View Assets</a>
            </div>
        </div>
    </div>
</div>

{% include "partials/_messages.html" %}

{% endblock content %}